services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    restart: unless-stopped
    depends_on:
      - app

  app:
    image: luna_manga:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/dist:/root/main/dist
    ports:
      - 8000
    deploy:
      mode: replicated
      replicas: 1
    restart: unless-stopped
    command: sh -c "serve -s dist -l 8000"
