import react from "@vitejs/plugin-react";
import path from "path";
import { defineConfig } from "vite";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@constants": path.resolve(__dirname, "./src/constants"),
      "@src": path.resolve(__dirname, "./src"),
      "@assets": path.resolve(__dirname, "./src/assets"),
      "@components": path.resolve(__dirname, "./src/components"),
      "@enums": path.resolve(__dirname, "./src/enums"),
      "@interfaces": path.resolve(__dirname, "./src/interfaces"),
      "@middlewares": path.resolve(__dirname, "./src/middlewares"),
      "@mocks": path.resolve(__dirname, "./src/mocks"),
      "@models": path.resolve(__dirname, "./src/models"),
      "@pages": path.resolve(__dirname, "./src/pages"),
      "@repositories": path.resolve(__dirname, "./src/repositories"),
      "@routes": path.resolve(__dirname, "./src/routes"),
      "@services": path.resolve(__dirname, "./src/services"),
      "@store": path.resolve(__dirname, "./src/store"),
      "@utils": path.resolve(__dirname, "./src/utils"),
    },
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
          "react-vendor": ["react", "react-dom", "react-router-dom", "react-redux", "@reduxjs/toolkit"],
          "react-toastify": ["react-toastify"],
          "react-beautiful-dnd": ["react-beautiful-dnd"],
          "date-picker": ["react-datepicker"],
          slate: ["slate", "slate-history", "slate-react"],
          "styled-components": ["styled-components"],
          swiper: ["swiper"],
          axios: ["axios"],
          "js-cookie": ["js-cookie"],

          FrontSideReducers: ["@store/FrontSideReducers"],
          BackofficeReducers: ["@store/BackofficeReducers"],

          FrontsideAuthService: ["@services/frontside/AuthService"],
          FrontsideBookmarkService: ["@services/frontside/BookmarkService"],
          FrontsideCategoryService: ["@services/frontside/CategoryService"],
          FrontsideCategoryStoryService: ["@services/frontside/CategoryStoryService"],
          FrontsideChapterCommentService: ["@services/frontside/ChapterCommentService"],
          FrontsideChapterService: ["@services/frontside/ChapterService"],
          FrontsideCookieService: ["@services/frontside/CookieService"],
          FrontsideCustomerProfileService: ["@services/frontside/CustomerProfileService"],
          FrontsideCustomerReportService: ["@services/frontside/CustomerReportService"],
          FrontsideEditCustomerProfileService: ["@services/frontside/EditCustomerProfileService"],
          FrontsideFileService: ["@services/frontside/FileService"],
          FrontsideProfilePostService: ["@services/frontside/ProfilePostService"],
          FrontsideProfileService: ["@services/frontside/ProfileService"],
          FrontsideSignInSignUpService: ["@services/frontside/SignInSignUpService"],
          FrontsideStoryChapterService: ["@services/frontside/StoryChapterService"],
          FrontsideStorySearchService: ["@services/frontside/StorySearchService"],
          FrontsideStoryService: ["@services/frontside/StoryService"],
          FrontsideThemeService: ["@services/frontside/ThemeService"],
          FrontsideWidgetOnPageService: ["@services/frontside/WidgetOnPageService"],
          FrontsideWidgetService: ["@services/frontside/WidgetService"],

          BackofficeAuthService: ["@services/backoffice/AuthService"],
          BackofficeBannerCreateEditService: ["@services/backoffice/BannerCreateEditService"],
          BackofficeBannerListService: ["@services/backoffice/BannerListService"],
          BackofficeBannerService: ["@services/backoffice/BannerService"],
          BackofficeCategoryCreateEditService: ["@services/backoffice/CategoryCreateEditService"],
          BackofficeCategoryListService: ["@services/backoffice/CategoryListService"],
          BackofficeCategoryService: ["@services/backoffice/CategoryService"],
          BackofficeChapterCreateEditService: ["@services/backoffice/ChapterCreateEditService"],
          BackofficeChapterListService: ["@services/backoffice/ChapterListService"],
          BackofficeChapterService: ["@services/backoffice/ChapterService"],
          BackofficeCookieService: ["@services/backoffice/CookieService"],
          BackofficeCustomerEditService: ["@services/backoffice/CustomerEditService"],
          BackofficeCustomerGroupCreateEditService: ["@services/backoffice/CustomerGroupCreateEditService"],
          BackofficeCustomerGroupListService: ["@services/backoffice/CustomerGroupListService"],
          BackofficeCustomerGroupService: ["@services/backoffice/CustomerGroupService"],
          BackofficeCustomerListService: ["@services/backoffice/CustomerListService"],
          BackofficeCustomerReportListService: ["@services/backoffice/CustomerReportListService"],
          BackofficeCustomerReportService: ["@services/backoffice/CustomerReportService"],
          BackofficeCustomerService: ["@services/backoffice/CustomerService"],
          BackofficeDashboardService: ["@services/backoffice/DashboardService"],
          BackofficeFileService: ["@services/backoffice/FileService"],
          BackofficePermissionListService: ["@services/backoffice/PermissionListService"],
          BackofficeSignInService: ["@services/backoffice/SignInService"],
          BackofficeStoryCreateEditService: ["@services/backoffice/StoryCreateEditService"],
          BackofficeStoryListService: ["@services/backoffice/StoryListService"],
          BackofficeStoryService: ["@services/backoffice/StoryService"],
          BackofficeThemeService: ["@services/backoffice/ThemeService"],
          BackofficeUserCreateEditService: ["@services/backoffice/UserCreateEditService"],
          BackofficeUserListService: ["@services/backoffice/UserListService"],
          BackofficeUserProfileService: ["@services/backoffice/UserProfileService"],
          BackofficeUserRoleCreateEditService: ["@services/backoffice/UserRoleCreateEditService"],
          BackofficeUserRoleListService: ["@services/backoffice/UserRoleListService"],
          BackofficeUserRoleService: ["@services/backoffice/UserRoleService"],
          BackofficeUserService: ["@services/backoffice/UserService"],
          BackofficeWidgetCreateEditService: ["@services/backoffice/WidgetCreateEditService"],
          BackofficeWidgetListService: ["@services/backoffice/WidgetListService"],
          BackofficeWidgetSequenceService: ["@services/backoffice/WidgetSequenceService"],
          BackofficeWidgetService: ["@services/backoffice/WidgetService"],

          UtilsBannerCreateUpdateHelpers: ["@utils/BannerCreateUpdateHelpers"],
          UtilsCategoryCreateUpdateHelpers: ["@utils/CategoryCreateUpdateHelpers"],
          UtilsChapterCreateUpdateHelpers: ["@utils/ChapterCreateUpdateHelpers"],
          UtilsCustomerGroupUpdateHelpers: ["@utils/CustomerGroupUpdateHelpers"],
          UtilsCustomerUpdateHelpers: ["@utils/CustomerUpdateHelpers"],
          UtilsHelpers: ["@utils/Helpers"],
          UtilsHooks: ["@utils/Hooks"],
          UtilsImageService: ["@utils/ImageService"],
          UtilsMockService: ["@utils/MockService"],
          UtilsScreenService: ["@utils/ScreenService"],
          UtilsSlateService: ["@utils/SlateService"],
          UtilsStoryCreateUpdateHelpers: ["@utils/StoryCreateUpdateHelpers"],
          UtilsThemes: ["@utils/Themes"],
          UtilsUserRoleUpdateHelpers: ["@utils/UserRoleUpdateHelpers"],
          UtilsUserUpdateHelpers: ["@utils/UserUpdateHelpers"],
          UtilsWidgetCreateUpdateHelpers: ["@utils/WidgetCreateUpdateHelpers"],
        },
      },
    },
    chunkSizeWarningLimit: 500,
  },
});
