services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.setuphttps.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    depends_on:
      - app

  app:
    image: teeratachdocker/luna_manga:latest
    ports:
      - 8000
    restart: unless-stopped
    command: sh -c "serve -s dist -l 8000"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
