export enum PermissionDisplayEnum {
  STORY = "Story",
  CHAPTER = "Chapter",
  CATEGORY = "Category",
  CUSTOMER = "Customers",
  CUSTOMER_GROUP = "Customer Groups",
  USER = "Users",
  USER_ROLE = "Roles",
  BANNER = "Banners",
  WIDGET = "Widgets",
  CUSTOMER_REPORT = "Customer Reports",
  FILE = "File",
  OAUTH_CLIENT = "OAuth Client",
}

export enum PermissionSlugEnum {
  STORY = "story",
  CHAPTER = "chapter",
  CATEGORY = "category",
  CUSTOMERS = "customer",
  CUSTOMER_GROUPS = "customer_group",
  USER = "user",
  ROLE = "roles_and_permission",
  BANNER = "banner",
  WIDGET = "widget",
  CUSTOMER_REPORT = "customer_report",
  FILE = "file",
  OAUTH_CLIENT = "oauth_client",
}

export enum PermissionEnum {
  STORY_VIEW = "story.view",
  STORY_MANGE = "story.manage",
  CHAPTER_VIEW = "chapter.view",
  CHAPTER_MANGE = "chapter.manage",
  CATEGORY_VIEW = "category.view",
  CATEGORY_MANGE = "category.manage",
  CUSTOMERS_VIEW = "customer.view",
  CUSTOMERS_MANGE = "customer.manage",
  CUSTOMER_GROUPS_VIEW = "customer_group.view",
  CUSTOMER_GROUPS_MANGE = "customer_group.manage",
  USER_VIEW = "user.view",
  USER_MANGE = "user.manage",
  ROLE_VIEW = "roles_and_permission.view",
  ROLE_MANGE = "roles_and_permission.manage",
  BANNER_VIEW = "banner.view",
  BANNER_MANGE = "banner.manage",
  WIDGET_VIEW = "widget.view",
  WIDGET_MANGE = "widget.manage",
  CUSTOMER_REPORT_VIEW = "customer_report.view",
  CUSTOMER_REPORT_MANGE = "customer_report.manage",
  FILE_VIEW = "file.view",
  FILE_MANGE = "file.manage",
  OAUTH_CLIENT_VIEW = "oauth_client.view",
  OAUTH_CLIENT_MANGE = "oauth_client.manage",
}
